### ISSUE TITLE
Building does not work on Ubuntu 16.04.

### ISSUE THREAD

**Issue by patrykbajos** [SimonKagstrom/emilpro#51]
Compilation failed on my Ubuntu 16.04.
I have installed all dependencies `sudo apt-get install libelf-dev libgtkmm-3.0-dev libgtksourceviewmm-3.0-dev libxml++2.6-dev libcurl3-dev libcapstone-dev flex bison`.

My log is:
[http://pastebin.com/Gzv6hFx7](http://pastebin.com/Gzv6hFx7)

**Comment by SimonKagstrom** [comment]
Yes, makeinfo is also needed. Should probably go in the INSTALL file.

There is also a Qt port, which is in many ways better and can be built with cmake targeting the `src/qt/` directory.
