### ISSUE TITLE
Build failure in binutils

### ISSUE THREAD

**Issue by pcordes** [SimonKagstrom/emilpro#31]
Current git head doesn't build on Ubuntu 15.04.

The error is from `make` is:

```
...
ft32-tdep.c: In function ‘ft32_skip_prologue’:
ft32-tdep.c:253:8: error: incompatible types when assigning to type ‘struct symbol *’ from type ‘struct block_symbol’
    sym = lookup_symbol (func_name, NULL, VAR_DOMAIN, NULL);
        ^
Makefile:1135: recipe for target 'ft32-tdep.o' failed
...
```

More context:

```
checking for x86_64-unknown-linux-gnu-ranlib... ranlib
checking for x86_64-unknown-linux-gnu-ar... ar
configure: updating cache .././config.cache
configure: creating ./config.status
config.status: creating Makefile
config.status: creating import/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing default commands
=== configuring in build-libiberty-gdbserver (/usr/local/src/emilpro/build/binutils/gdb/gdbserver/build-libiberty-gdbserver)
configure: running /bin/bash .././../../libiberty/configure --disable-option-checking '--prefix=/usr/local/src/emilpro/build/binutils/../install-binutils'  '--with-gnu-as' '--disable-werror' '--enable-targets=all' '--disable-ld' '--disable-gold' '--program-transform-name=s,y,y,' '--build=x86_64-unknown-linux-gnu' '--host=x86_64-unknown-linux-gnu' '--target=x86_64-unknown-linux-gnu' 'build_alias=x86_64-unknown-linux-gnu' 'host_alias=x86_64-unknown-linux-gnu' 'target_alias=x86_64-unknown-linux-gnu' 'CC=gcc' 'CFLAGS=-g -O2' 'LDFLAGS=-static-libstdc++ -static-libgcc ' 'CXX=g++' 'CXXFLAGS=-g -O2' 'MAKEINFO=makeinfo --split-size=5000000' 'YACC=bison -y' --cache-file=.././config.cache --srcdir=.././../../libiberty
configure: loading cache .././config.cache
checking whether to enable maintainer-specific portions of Makefiles... no
checking for makeinfo... makeinfo --split-size=5000000
checking for perl... perl
checking build system type... (cached) x86_64-unknown-linux-gnu
checking host system type... (cached) x86_64-unknown-linux-gnu
checking for x86_64-unknown-linux-gnu-ar... (cached) ar
checking for x86_64-unknown-linux-gnu-ranlib... (cached) ranlib
checking whether to install libiberty headers and static library... no
configure: target_header_dir =
checking for x86_64-unknown-linux-gnu-gcc... (cached) gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables...
checking for suffix of object files... (cached) o
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking how to run the C preprocessor... (cached) gcc -E
checking for grep that handles long lines and -e... (cached) /bin/grep
checking for egrep... (cached) /bin/grep -E
checking for ANSI C header files... (cached) yes
checking for sys/types.h... (cached) yes
checking for sys/stat.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for memory.h... (cached) yes
checking for strings.h... (cached) yes
checking for inttypes.h... (cached) yes
checking for stdint.h... (cached) yes
checking for unistd.h... (cached) yes
checking for minix/config.h... (cached) no
checking whether it is safe to define __EXTENSIONS__... (cached) yes
checking for special C compiler options needed for large files... (cached) no
checking for _FILE_OFFSET_BITS value needed for large files... (cached) no
checking whether gcc supports -W... yes
checking whether gcc supports -Wall... yes
checking whether gcc supports -Wwrite-strings... yes
checking whether gcc supports -Wc++-compat... yes
checking whether gcc supports -Wstrict-prototypes... yes
checking whether gcc supports -pedantic ... yes
checking whether gcc and cc understand -c and -o together... yes
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking whether byte ordering is bigendian... (cached) no
checking for a BSD-compatible install... /usr/bin/install -c
checking for sys/file.h... yes
checking for sys/param.h... (cached) yes
checking for limits.h... yes
checking for stdlib.h... (cached) yes
checking for malloc.h... yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking for strings.h... (cached) yes
checking for sys/time.h... (cached) yes
checking for time.h... yes
checking for sys/resource.h... yes
checking for sys/stat.h... (cached) yes
checking for sys/mman.h... (cached) yes
checking for fcntl.h... yes
checking for alloca.h... yes
checking for sys/pstat.h... no
checking for sys/sysmp.h... no
checking for sys/sysinfo.h... yes
checking for machine/hal_sysinfo.h... no
checking for sys/table.h... no
checking for sys/sysctl.h... yes
checking for sys/systemcfg.h... no
checking for stdint.h... (cached) yes
checking for stdio_ext.h... yes
checking for process.h... no
checking for sys/prctl.h... yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking whether time.h and sys/time.h may both be included... yes
checking whether errno must be declared... no
checking size of int... 4
checking size of long... 8
checking for long long... yes
checking size of long long... 8
checking for a 64-bit type... uint64_t
checking for intptr_t... yes
checking for uintptr_t... yes
checking for ssize_t... yes
checking for pid_t... (cached) yes
checking for library containing strerror... none required
checking for asprintf... yes
checking for atexit... yes
checking for basename... yes
checking for bcmp... yes
checking for bcopy... yes
checking for bsearch... yes
checking for bzero... yes
checking for calloc... yes
checking for clock... yes
checking for ffs... yes
checking for getcwd... (cached) yes
checking for getpagesize... yes
checking for gettimeofday... yes
checking for index... yes
checking for insque... yes
checking for memchr... yes
checking for memcmp... yes
checking for memcpy... yes
checking for memmem... (cached) yes
checking for memmove... yes
checking for mempcpy... (cached) yes
checking for memset... yes
checking for mkstemps... yes
checking for putenv... yes
checking for random... yes
checking for rename... yes
checking for rindex... yes
checking for setenv... yes
checking for snprintf... yes
checking for sigsetmask... yes
checking for stpcpy... yes
checking for stpncpy... yes
checking for strcasecmp... yes
checking for strchr... yes
checking for strdup... yes
checking for strncasecmp... yes
checking for strndup... yes
checking for strnlen... yes
checking for strrchr... yes
checking for strstr... yes
checking for strtod... yes
checking for strtol... yes
checking for strtoul... yes
checking for strtoll... yes
checking for strtoull... yes
checking for strverscmp... yes
checking for tmpnam... yes
checking for vasprintf... yes
checking for vfprintf... yes
checking for vprintf... yes
checking for vsnprintf... yes
checking for vsprintf... yes
checking for waitpid... yes
checking for setproctitle... no
checking whether alloca needs Cray hooks... no
checking stack direction for C alloca... -1
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking for _doprnt... no
checking for sys_errlist... yes
checking for sys_nerr... yes
checking for sys_siglist... yes
checking for external symbol _system_configuration... no
checking for __fsetlocking... yes
checking for canonicalize_file_name... (cached) yes
checking for dup3... yes
checking for getrlimit... yes
checking for getrusage... yes
checking for getsysinfo... no
checking for gettimeofday... (cached) yes
checking for on_exit... yes
checking for psignal... yes
checking for pstat_getdynamic... no
checking for pstat_getstatic... no
checking for realpath... (cached) yes
checking for setrlimit... yes
checking for sbrk... yes
checking for spawnve... no
checking for spawnvpe... no
checking for strerror... yes
checking for strsignal... yes
checking for sysconf... yes
checking for sysctl... yes
checking for sysmp... no
checking for table... no
checking for times... yes
checking for wait3... yes
checking for wait4... yes
checking whether basename is declared... yes
checking whether ffs is declared... yes
checking whether asprintf is declared... yes
checking whether vasprintf is declared... yes
checking whether snprintf is declared... (cached) yes
checking whether vsnprintf is declared... (cached) yes
checking whether calloc is declared... yes
checking whether getenv is declared... yes
checking whether getopt is declared... yes
checking whether malloc is declared... yes
checking whether realloc is declared... yes
checking whether sbrk is declared... yes
checking whether strtol is declared... yes
checking whether strtoul is declared... yes
checking whether strtoll is declared... (cached) yes
checking whether strtoull is declared... (cached) yes
checking whether strverscmp is declared... (cached) yes
checking whether canonicalize_file_name must be declared... no
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for getpagesize... (cached) yes
checking for working mmap... yes
checking for working strncmp... yes
configure: updating cache .././config.cache
configure: creating ./config.status
config.status: creating Makefile
config.status: creating testsuite/Makefile
config.status: creating config.h
config.status: executing default commands
checking for sgtty.h... (cached) yes
checking for termio.h... (cached) yes
checking for termios.h... (cached) yes
checking for sys/reg.h... (cached) yes
checking for string.h... (cached) yes
checking for proc_service.h... (cached) no
checking for sys/procfs.h... (cached) yes
checking linux/elf.h usability... yes
checking linux/elf.h presence... yes
checking for linux/elf.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for signal.h... (cached) yes
checking for sys/file.h... (cached) yes
checking for sys/ioctl.h... (cached) yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking for sys/socket.h... (cached) yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/tcp.h usability... yes
checking netinet/tcp.h presence... yes
checking for netinet/tcp.h... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking for getauxval... (cached) yes
checking for pread... (cached) yes
checking for pwrite... (cached) yes
checking for pread64... (cached) yes
checking for setns... (cached) yes
checking for ANSI C header files... (cached) yes
checking for working alloca.h... (cached) yes
checking for alloca... (cached) yes
checking for nl_langinfo and CODESET... (cached) yes
checking for linux/perf_event.h... (cached) yes
checking for locale.h... (cached) yes
checking for memory.h... (cached) yes
checking for signal.h... (cached) yes
checking for sys/resource.h... (cached) yes
checking for sys/socket.h... (cached) yes
checking for sys/syscall.h... (cached) yes
checking for sys/un.h... (cached) yes
checking for sys/wait.h... (cached) yes
checking for thread_db.h... (cached) yes
checking for wait.h... (cached) yes
checking for fdwalk... (cached) no
checking for getrlimit... (cached) yes
checking for pipe... (cached) yes
checking for pipe2... (cached) yes
checking for socketpair... (cached) yes
checking whether strerror is declared... (cached) yes
checking whether strstr is declared... (cached) yes
checking for sigsetjmp... (cached) yes
checking for sys/ptrace.h... (cached) yes
checking for ptrace.h... (cached) no
checking whether ptrace is declared... (cached) yes
checking return type of ptrace... (cached) long
checking types of arguments for ptrace... (cached) enum __ptrace_request,int,long,long
checking for ust... no
checking compiler warning flags...  -Wall -Wpointer-arith -Wformat-nonliteral -Wno-char-subscripts -Wempty-body -Wdeclaration-after-statement
checking for dladdr... yes
checking for long long... (cached) yes
checking size of long long... (cached) 8
checking whether basename is declared... (cached) yes
checking whether ffs is declared... (cached) yes
checking whether asprintf is declared... (cached) yes
checking whether vasprintf is declared... (cached) yes
checking whether snprintf is declared... (cached) yes
checking whether vsnprintf is declared... (cached) yes
checking whether strtol is declared... (cached) yes
checking whether strtoul is declared... (cached) yes
checking whether strtoll is declared... (cached) yes
checking whether strtoull is declared... (cached) yes
checking whether strverscmp is declared... (cached) yes
checking whether strerror is declared... (cached) yes
checking whether perror is declared... yes
checking whether vasprintf is declared... (cached) yes
checking whether vsnprintf is declared... (cached) yes
checking for struct stat.st_blocks... (cached) yes
checking for struct stat.st_blksize... (cached) yes
checking for socklen_t... (cached) yes
checking for Elf32_auxv_t... yes
checking for Elf64_auxv_t... yes
checking for PTRACE_GETREGS... yes
checking for PTRACE_GETFPXREGS... yes
checking for lwpid_t in sys/procfs.h... (cached) yes
checking for psaddr_t in sys/procfs.h... (cached) yes
checking for prgregset_t in sys/procfs.h... (cached) yes
checking for prfpregset_t in sys/procfs.h... (cached) yes
checking for elf_fpregset_t in sys/procfs.h... yes
checking for dlopen in -ldl... yes
checking for the dynamic export flag... -Wl,--dynamic-list
checking for TD_VERSION... yes
checking whether the target supports __sync_*_compare_and_swap... yes
checking whether ADDR_NO_RANDOMIZE is declared... (cached) yes
configure: updating cache .././config.cache
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
config.status: executing depdir commands
mkdir -p -- .deps
config.status: executing default commands
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing default commands
config.status: executing depdir commands
Creating observer.htmp
Moving observer.htmp to observer.h
Creating observer.itmp
Moving observer.itmp to observer.inc
config.status: creating Makefile
config.status: executing depfiles commands
ft32-tdep.c: In function ‘ft32_skip_prologue’:
ft32-tdep.c:253:8: error: incompatible types when assigning to type ‘struct symbol *’ from type ‘struct block_symbol’
    sym = lookup_symbol (func_name, NULL, VAR_DOMAIN, NULL);
        ^
Makefile:1135: recipe for target 'ft32-tdep.o' failed
make[5]: *** [ft32-tdep.o] Error 1
Makefile:10063: recipe for target 'all-gdb' failed
make[4]: *** [all-gdb] Error 2
Makefile:845: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/binutils.dir/build.make:51: recipe for target 'binutils/.binutils-built' failed
make[2]: *** [binutils/.binutils-built] Error 2
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/binutils.dir/all' failed
make[1]: *** [CMakeFiles/binutils.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2
peter@tesla:/usr/local/src/emilpro/build$
```

CMake found all the libraries it was looking for, but did output a warning.  IDK if it's significant, but here it is:

```
peter@tesla:/usr/local/src/emilpro/build$ cmake ..
CMake Warning (dev) at CMakeLists.txt:138 (add_executable):
  Policy CMP0037 is not set: Target names should not be reserved and should
  match a validity pattern.  Run "cmake --help-policy CMP0037" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  The target name "tools/squash-instruction-models" is reserved or not valid
  for certain CMake features, such as generator expressions, and may result
  in undefined behavior.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/src/emilpro/build
```

**Comment by SimonKagstrom** [comment]
Well, I suppose I should use a specific version of binutils - it now checks out the git HEAD, so it will sometimes fail simply because binutils itself fails!

I'll fix that. I have some more pressing real-life tasks for now though (just got another kid :-)), so even smaller fixes like this might take a while!

**Comment by pcordes** [comment]
On Sun, Aug 02, 2015 at 07:09:49AM -0700, Simon Kagstrom wrote:
> Well, I suppose I should use a specific version of binutils - it now checks out the git HEAD, so it will sometimes fail simply because binutils itself fails!
> 
> I'll fix that. I have some more pressing real-life tasks for now though (just got another kid :-)), so even smaller fixes like this might take a while!

 Congrats on the kid :)
 
 If I get around to taking a look at this and fixing it, I'll send a
pull-request.  Maybe there's a stable branch of binutils?  Anyway,
thanks for the reply.

You said (on my other ticket) that you can't use distro-packaged
binutils-dev because it's not multiarch.  objdump -d can disassemble x86
and x86-64 binaries, but is that something different?  Sorry I'm lazy
and should just google this. :P

-- 
#define X(x,y) x##y
Peter Cordes ;  e-mail: X(peter@cor , des.ca)

"The gods confound the man who first found out how to distinguish the hours!
 Confound him, too, who in this place set up a sundial, to cut and hack
 my day so wretchedly into small pieces!" -- Plautus, 200 BC

**Comment by SimonKagstrom** [comment]
... But not ARM, MIPS, Cris etc etc. :-). The multi-arch binutils supports
literally dozens of architectures.

**Comment by SimonKagstrom** [comment]
Fixed with 25c76a3.
